substitutions:
  name: "louder-esp32"
  friendly_name: Louder-ESP32 Media Player
  pcb_version: "J"

esphome:
  name: "${name}"
  name_add_mac_suffix: false
  includes:
    - include/louderesp32-s3.h
  platformio_options:
    lib_deps: "Wire"
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
  on_boot:
    priority: 800
    then:
    ## Set a volume limit just to be safe...
    - media_player.volume_set:
        id: louderesp32
        volume: 20%

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: arduino

### Optional if you want ethernet (then remove all wifi config) ###
#ethernet:
#  type: W5500
#  clk_pin: GPIO12
#  mosi_pin: GPIO11
#  miso_pin: GPIO13
#  cs_pin: GPIO10
#  interrupt_pin: GPIO6
#  reset_pin: GPIO5

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:
    encryption: 
      key: !secret esphome_api_key

# Allow Over-The-Air updates
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  ap:
    ssid: "$name Hotspot"
    password: "squeezebox"

captive_portal:

psram:
  mode: octal
  speed: 80MHz

switch:
  - platform: custom
    lambda: |-
      auto tas5805 = new TAS5805();
      App.register_component(tas5805);
      return {tas5805};
    switches:
      name: "Enable Amp"
      id: amp

i2c:
  sda: GPIO8
  scl: GPIO9
  scan: True
  id: i2c_component

i2s_audio:
  i2s_lrclk_pin: GPIO15
  i2s_bclk_pin: GPIO14

media_player:
  - platform: i2s_audio
    name: $friendly_name
    id: louderesp32
    dac_type: external
    i2s_dout_pin: GPIO16
    mode: stereo
    on_play:
      - switch.turn_on: amp
